use_frameworks!
platform :ios, '8.0'

target 'JWInfiniteCollectionView_Example' do
  pod 'JWInfiniteCollectionView', :path => '../'

  target 'JWInfiniteCollectionView_Tests' do
    inherit! :search_paths

    
  end
end
