use_frameworks!
platform :ios, '8.0'

target 'JWInfiniteCycleView_Example' do
  pod 'JWInfiniteCycleView', :path => '../'

  target 'JWInfiniteCycleView_Tests' do
    inherit! :search_paths

    
  end
end
